---
title: "Design files for ch4-238, Beulah reservoir, under 'average' water levels"
author: "J. Beaulieu"
date: "4/2/2020"
output: html_document
---


```{r, echo=FALSE}
# Want to create .html that is nice and clean for field crews.  Should only print out maps and coordinate table.
# Using trick below to force components to print on separate pages.

# trick for forcing a page break when printing .html
#URL for inserting hard page breaks for print html
#https://stackoverflow.com/questions/25240541/how-to-add-newpage-in-rmarkdown-in-a-smart-way
```


```{r, echo=FALSE, message=FALSE}
library(leaflet)
library(sf)
library(tidyr)
```




```{r, echo=FALSE, message=FALSE, results="hide"}
# see SuRGE/lakeDsn/R10/ch4_238 beulah/ch4_238_average/ch4_238_average.R for origin of these data

# survey design points
averageSitesWGS238 <- st_read(dsn = "../../../../../../../lakeDsn/R10/ch4_238 beulah/ch4_238_average",
                              layer = "averageAllSitesWGS238")

# lake polygon
averageWGS238 <- st_read(dsn = "../../../../../../../lakeDsn/R10/ch4_238 beulah/ch4_238_average",
                             layer = "averageWGS238") 


```
<P style="page-break-before: always">

Print from Internet Explorer for best quality.

## Main Sites
```{r, echo=FALSE, out.width= "100%"}

# leaflet colors
factpal <- colorFactor(topo.colors(3), averageWGS238$section)
factpal.points <- colorFactor(palette = c("red", "black"), domain = averageSitesWGS238$panel)

# All points
leaflet() %>%
  addProviderTiles(providers$Esri.WorldImagery) %>%
  fitBounds(lng1 = min(st_coordinates(averageSitesWGS238)[,1]),
            lng2 = max(st_coordinates(averageSitesWGS238)[,1]),
            lat1 = min(st_coordinates(averageSitesWGS238)[,2]),
            lat2 = max(st_coordinates(averageSitesWGS238)[,2])) %>%
  addPolygons(data = averageWGS238,
              color = "black", weight = 1,
              fillColor = ~factpal(section)) %>%
  addCircleMarkers(data = averageSitesWGS238,
                   fillColor = ~factpal.points(panel),
                   fillOpacity = 1,
                   stroke = FALSE,
                   radius = ~ifelse(panel == "mainSites", 10, 4),
                   label = ~siteID,
                   labelOptions = labelOptions(noHide = T, textOnly = TRUE,
                                               style = list(
                                                 color = "white",
                                                 "font-size" = "15px",
                                                 "font-family" = "serif"))) %>%
  addLegend(position = "bottomright", pal = factpal.points,
            values = as.character(averageSitesWGS238$panel),
            title = "Sample sites") %>%
  addLegend(position = "bottomright", pal = factpal,
            values = as.character(averageWGS238$section),
            title = "sections") %>%
  addScaleBar()

```
<P style="page-break-before: always">
  
  

## Oversample Sites
```{r, echo=FALSE, out.width="100%"}

#this throwing error
leaflet() %>%
  addProviderTiles(providers$Esri.WorldImagery) %>%
  fitBounds(lng1 = min(st_coordinates(averageSitesWGS238)[,1]),
            lng2 = max(st_coordinates(averageSitesWGS238)[,1]),
            lat1 = min(st_coordinates(averageSitesWGS238)[,2]),
            lat2 = max(st_coordinates(averageSitesWGS238)[,2])) %>%
  addPolygons(data = averageWGS238,
              color = "black", weight = 1,
              fillColor = ~factpal(section)) %>%
  addCircleMarkers(data = filter(averageSitesWGS238, panel == "OverSamp"),
                   fillColor = "black", # manual color specification
                   fillOpacity = 1,
                   stroke = FALSE,
                   radius = 6,
                   label = ~siteID,
                   labelOptions = labelOptions(noHide = T, textOnly = TRUE,
                                               style = list(
                                                 color = "white",
                                                 "font-size" = "15px",
                                                 "font-family" = "serif"))) %>%
  # Rather than using pal and values, you can explicitly pass in colors and labels
  addLegend(position = "bottomright",
            color = "black", # manual 'color' specification
            labels = "OverSamp", # manual 'labels' specification
            title = "Sample sites") %>%
  addLegend(position = "bottomright", pal = factpal,
            values = as.character(averageWGS238$section),
            title = "sections") %>%
  addScaleBar()
```

<P style="page-break-before: always">
## Site Coordinates
```{r, echo=FALSE, }

# this is failing.  Can't figure out why
 # coords <- read.table(file = "../../../../../../../lakeDsn/R10/ch4_238 beulah/ch4_238_average/ch4_238_averageSites.txt",
 #                      header = TRUE, sep = "\t")

# Absolute path approach.  Need to fix
coords <- read.table(file = "C:/Users/JBEAULIE/Environmental Protection Agency (EPA)/SuRGE Survey of Reservoir Greenhouse gas Emissions - Documents/lakeDsn/R10/ch4_238 beulah/ch4_238_average/ch4_238_averageSites.txt",
                     header = TRUE, sep = "\t")

knitr::kable(coords)
```

